# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Heathrowairport
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: HeathrowairportMSP

        # ID to load the MSP definition as
        ID: HeathrowairportMSP

        MSPDir: crypto-config/peerOrganizations/heathrowairport.ibs.aero/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HeathrowairportMSP.admin', 'HeathrowairportMSP.peer', 'HeathrowairportMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('HeathrowairportMSP.admin', 'HeathrowairportMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('HeathrowairportMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.heathrowairport.ibs.aero
              Port: 11051
