server:
  port: 8090

spring:
  application:
    name: "aodb-kafaka-consumer"


#kafka configuration


kafka:
  brokers: localhost:9092
  reconnect-backoff-ms: 2000
  max-block-ms: 5000

fly2plan:
  kafka_topic:
    apllication: aodb


#kafka consumer-producer configs
#kafkaProducerConsumerProperties: ?brokers={{kafka.brokers}}&valueDeserializer={{kafka.deserializer-class}}&serializerClass={{kafka.serializer-class}}&maxBlockMs={{kafka.max-block-ms}}&reconnectBackoffMaxMs={{kafka.reconnect-backoff-ms}}

#kafka-uri-base: kafka:AODB-TOPIC

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always