NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.britishairways.ibs.aero-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.britishairways.ibs.aero-cert.pem
    OrganizationalUnitIdentifier: peer
