# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ibs.aero:
  peer0.birtishairways.ibs.aero:
  peer1.birtishairways.ibs.aero:
  peer0.gatewick.ibs.aero:
  peer1.gatewick.ibs.aero:
  ca.birtishairways.ibs.aero:
  ca.gatewick.ibs.aero:

networks:
  byfn:

services:
  ca.birtishairways.ibs.aero:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.birtishairways.ibs.aero
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.birtishairways.ibs.aero-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.Birtishairways.example.com_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/birtishairways.ibs.aero/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.birtishairways.ibs.aero
    networks:
      - byfn

  ca.gatewick.ibs.aero:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.gatewick.ibs.aero
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.gatewick.ibs.aero-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.gatewick.example.com_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/gatewick.ibs.aero/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.gatewick.ibs.aero
    networks:
      - byfn
  
  orderer.ibs.aero:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ibs.aero
    container_name: orderer.ibs.aero
    networks:
      - byfn

  orderer2.ibs.aero:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer2.ibs.aero
    container_name: orderer2.ibs.aero
    networks:
      - byfn
  
  orderer3.ibs.aero:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer3.ibs.aero
    container_name: orderer3.ibs.aero
    networks:
      - byfn
    
  orderer4.ibs.aero:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer4.ibs.aero
    container_name: orderer4.ibs.aero
    networks:
      - byfn

  orderer5.ibs.aero:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer5.ibs.aero
    container_name: orderer5.ibs.aero
    networks:
      - byfn

  peer0.birtishairways.ibs.aero:
    container_name: peer0.birtishairways.ibs.aero
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.birtishairways.ibs.aero
    networks:
      - byfn

  peer1.birtishairways.ibs.aero:
    container_name: peer1.birtishairways.ibs.aero
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.birtishairways.ibs.aero
    networks:
      - byfn

  peer0.gatewick.ibs.aero:
    container_name: peer0.gatewick.ibs.aero
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.gatewick.ibs.aero
    networks:
      - byfn

  peer1.gatewick.ibs.aero:
    container_name: peer1.gatewick.ibs.aero
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.gatewick.ibs.aero
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.birtishairways.ibs.aero:7051
      - CORE_PEER_LOCALMSPID=BirtishairwaysMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/birtishairways.ibs.aero/peers/peer0.birtishairways.ibs.aero/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/birtishairways.ibs.aero/peers/peer0.birtishairways.ibs.aero/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/birtishairways.ibs.aero/peers/peer0.birtishairways.ibs.aero/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/birtishairways.ibs.aero/users/Admin@birtishairways.ibs.aero/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ibs.aero
      - orderer2.ibs.aero
      - orderer3.ibs.aero
      - orderer4.ibs.aero
      - orderer5.ibs.aero
      - peer0.birtishairways.ibs.aero
      - peer1.birtishairways.ibs.aero
      - peer0.gatewick.ibs.aero
      - peer1.gatewick.ibs.aero
      - ca.birtishairways.ibs.aero
      - ca.gatewick.ibs.aero
    networks:
      - byfn
