# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  peer1.britishairways.ibs.aero:
networks:
  bymn:
    external:
      name: $SWARM_NETWORK
    
services:
  org1peer1:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.britishairways.ibs.aero
      - CORE_PEER_ADDRESS=peer1.britishairways.ibs.aero:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.britishairways.ibs.aero:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.britishairways.ibs.aero:8051
      - CORE_PEER_LOCALMSPID=BritishairwaysMSP
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_EXECUTETIMEOUT=800s

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/britishairways.ibs.aero/peers/peer1.britishairways.ibs.aero/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/britishairways.ibs.aero/peers/peer1.britishairways.ibs.aero/tls:/etc/hyperledger/fabric/tls
        - peer1.britishairways.ibs.aero:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG1_HOSTNAME

    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer1.britishairways.ibs.aero
 
                 
